"""Unit tests for the standards mirror (`sync_standards`) and the platform
audit suite orchestrator (`run_all`)."""
from __future__ import annotations

from pathlib import Path

import pytest

from bedrock.tools import run_all, sync_standards

_HEADER = "<!-- AUTOGENERATED MIRROR FROM BEDROCK PLATFORM. DO NOT EDIT LOCALLY. -->"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _make_source(tmp_path: Path) -> Path:
    source = tmp_path / "bedrock-source"
    _write(source / "docs" / "standards" / "s001-no-duplicate-ui-code.md", "# Standard S001\n\nBody.\n")
    _write(source / "docs" / "standards" / "s012-dual-pin-platform-governance.md", "# Standard S012\n\nBody.\n")
    _write(source / "docs" / "standards" / "s100-domain-standard-authoring.md", "# Standard S100\n\nBody.\n")
    return source


def _make_target(tmp_path: Path) -> Path:
    target = tmp_path / "consumer"
    target.mkdir()
    return target


# ---------------------------------------------------------------------------
# sync_standards
# ---------------------------------------------------------------------------


def test_sync_copies_canonical_standards_with_header(tmp_path: Path):
    source = _make_source(tmp_path)
    target = _make_target(tmp_path)

    exit_code = sync_standards.main(["--root", str(target), "--source", str(source)])

    assert exit_code == 0
    mirrored = (target / "docs" / "standards" / "s001-no-duplicate-ui-code.md").read_text(encoding="utf-8")
    assert mirrored.startswith(_HEADER)
    assert "Body." in mirrored
    assert (target / "docs" / "standards" / "s100-domain-standard-authoring.md").exists()


def test_sync_preserves_consumer_domain_standards(tmp_path: Path):
    source = _make_source(tmp_path)
    target = _make_target(tmp_path)
    domain_standard = target / "docs" / "standards" / "s101-collectit-listing-rules.md"
    _write(domain_standard, "# Standard S101\n\nConsumer-owned content.\n")

    sync_standards.main(["--root", str(target), "--source", str(source)])

    assert domain_standard.read_text(encoding="utf-8") == "# Standard S101\n\nConsumer-owned content.\n"


def test_sync_check_returns_zero_when_mirrors_are_fresh(tmp_path: Path, capsys):
    source = _make_source(tmp_path)
    target = _make_target(tmp_path)
    sync_standards.main(["--root", str(target), "--source", str(source)])
    capsys.readouterr()

    exit_code = sync_standards.main(["--root", str(target), "--source", str(source), "--check"])

    assert exit_code == 0


def test_sync_check_returns_one_on_drift(tmp_path: Path, capsys):
    source = _make_source(tmp_path)
    target = _make_target(tmp_path)
    sync_standards.main(["--root", str(target), "--source", str(source)])
    drifted = target / "docs" / "standards" / "s001-no-duplicate-ui-code.md"
    drifted.write_text(drifted.read_text(encoding="utf-8") + "\nLocal edit.\n", encoding="utf-8")
    capsys.readouterr()

    exit_code = sync_standards.main(["--root", str(target), "--source", str(source), "--check"])
    output = capsys.readouterr().out

    assert exit_code == 1
    assert "s001-no-duplicate-ui-code.md" in output


def test_sync_check_returns_one_on_missing_mirror(tmp_path: Path, capsys):
    source = _make_source(tmp_path)
    target = _make_target(tmp_path)

    exit_code = sync_standards.main(["--root", str(target), "--source", str(source), "--check"])
    output = capsys.readouterr().out

    assert exit_code == 1
    assert "s001-no-duplicate-ui-code.md" in output


# ---------------------------------------------------------------------------
# run_all
# ---------------------------------------------------------------------------


class _FakeAuditModule:
    def __init__(self, exit_code: int) -> None:
        self.exit_code = exit_code
        self.calls: list[list[str]] = []

    def main(self, argv: list[str] | None = None) -> int:
        self.calls.append(list(argv or []))
        return self.exit_code


def test_run_all_returns_zero_when_all_audits_pass(tmp_path: Path, monkeypatch):
    fakes = [("s001", _FakeAuditModule(0)), ("s002", _FakeAuditModule(0))]
    monkeypatch.setattr(run_all, "AUDIT_MODULES", fakes)

    exit_code = run_all.main(["--root", str(tmp_path)])

    assert exit_code == 0


def test_run_all_returns_one_when_an_audit_fails(tmp_path: Path, monkeypatch):
    fakes = [("s001", _FakeAuditModule(0)), ("s002", _FakeAuditModule(1))]
    monkeypatch.setattr(run_all, "AUDIT_MODULES", fakes)

    exit_code = run_all.main(["--root", str(tmp_path)])

    assert exit_code == 1


def test_run_all_returns_two_on_configuration_error(tmp_path: Path, monkeypatch):
    fakes = [("s001", _FakeAuditModule(2)), ("s002", _FakeAuditModule(1))]
    monkeypatch.setattr(run_all, "AUDIT_MODULES", fakes)

    exit_code = run_all.main(["--root", str(tmp_path)])

    assert exit_code == 2


def test_run_all_respects_fail_fast(tmp_path: Path, monkeypatch):
    first = _FakeAuditModule(1)
    second = _FakeAuditModule(0)
    monkeypatch.setattr(run_all, "AUDIT_MODULES", [("s001", first), ("s002", second)])

    run_all.main(["--root", str(tmp_path), "--fail-fast"])

    assert len(first.calls) == 1
    assert len(second.calls) == 0


def test_run_all_without_fail_fast_runs_every_audit(tmp_path: Path, monkeypatch):
    first = _FakeAuditModule(1)
    second = _FakeAuditModule(0)
    monkeypatch.setattr(run_all, "AUDIT_MODULES", [("s001", first), ("s002", second)])

    run_all.main(["--root", str(tmp_path)])

    assert len(first.calls) == 1
    assert len(second.calls) == 1


def test_run_all_json_output_reports_every_audit_status(tmp_path: Path, monkeypatch, capsys):
    fakes = [("s001", _FakeAuditModule(0)), ("s002", _FakeAuditModule(1))]
    monkeypatch.setattr(run_all, "AUDIT_MODULES", fakes)
    capsys.readouterr()

    run_all.main(["--root", str(tmp_path), "--json"])
    output = capsys.readouterr().out

    assert '"s001"' in output
    assert '"s002"' in output
    assert "PASS" in output
    assert "FAIL" in output
