"""
Module:  sync_standards.py
Layer:   bedrock/tools
Desc:    Mirrors the canonical platform standards (`docs/standards/s001-*.md`
         through `s014-*.md`, plus `s100-*.md`) from the Bedrock source of
         truth into a downstream consumer repository (CollectIt, MLBTracker).

         A mirrored file gets a read-only header prepended so an editor
         opening it in the consumer repo knows not to hand-edit it - the
         platform owns S001-S099 (and the S100 authoring contract) and amends
         them centrally; a consumer edit would silently drift back out of
         sync the next time this tool runs.

         Consumer-authored domain standards (`s101-*.md` through `s199-*.md`,
         see S100) are never touched: this tool only ever writes filenames it
         itself recognizes as canonical.

         `--check` performs the same comparison without writing, for a CI
         drift gate: exit 0 when every mirror is present and byte-identical
         to what a real sync would produce, exit 1 with diff diagnostics
         otherwise.

Usage:   python -m bedrock.tools.sync_standards --root <consumer-repo>
         python -m bedrock.tools.sync_standards --root <consumer-repo> --check
"""
from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path

MIRROR_HEADER = "<!-- AUTOGENERATED MIRROR FROM BEDROCK PLATFORM. DO NOT EDIT LOCALLY. -->"

_STANDARD_FILENAME = re.compile(r"^s(\d{3})-.*\.md$")


def _is_canonical(filename: str) -> bool:
    match = _STANDARD_FILENAME.match(filename)
    if not match:
        return False
    number = int(match.group(1))
    return 1 <= number <= 14 or number == 100


def _canonical_source_files(source_root: Path) -> list[Path]:
    standards_dir = source_root / "docs" / "standards"
    if not standards_dir.is_dir():
        return []
    return sorted(p for p in standards_dir.glob("*.md") if _is_canonical(p.name))


def _mirrored_content(source_text: str) -> str:
    return f"{MIRROR_HEADER}\n\n{source_text}"


def _default_source_root() -> Path:
    # bedrock/tools/sync_standards.py -> bedrock -> bedrock-api -> packages -> <repo root>
    return Path(__file__).resolve().parents[4]


def sync_standards(source_root: Path, target_root: Path, check: bool) -> tuple[bool, list[str]]:
    """Mirror canonical standards from `source_root` into `target_root`.

    Returns `(ok, diagnostics)`. In `--check` mode nothing is written; `ok`
    reports whether every mirror is already fresh. Otherwise every canonical
    file is written and `ok` is always True.
    """
    target_dir = target_root / "docs" / "standards"
    diagnostics: list[str] = []
    ok = True

    for source_file in _canonical_source_files(source_root):
        expected = _mirrored_content(source_file.read_text(encoding="utf-8"))
        target_file = target_dir / source_file.name

        if check:
            if not target_file.exists():
                ok = False
                diagnostics.append(f"MISSING: {target_file} (source: {source_file.name})")
                continue
            actual = target_file.read_text(encoding="utf-8")
            if actual != expected:
                ok = False
                diff = "\n".join(
                    difflib.unified_diff(
                        actual.splitlines(),
                        expected.splitlines(),
                        fromfile=str(target_file),
                        tofile=f"<bedrock source>/{source_file.name}",
                        lineterm="",
                    )
                )
                diagnostics.append(f"DRIFT: {target_file}\n{diff}")
        else:
            target_dir.mkdir(parents=True, exist_ok=True)
            target_file.write_text(expected, encoding="utf-8")
            diagnostics.append(f"SYNCED: {target_file}")

    return ok, diagnostics


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, help="target consumer repository root")
    parser.add_argument(
        "--source",
        default=None,
        help="canonical bedrock repository root (defaults to this package's own repo)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify mirrors are fresh without writing; exit 1 on drift or missing files",
    )
    args = parser.parse_args(argv)

    target_root = Path(args.root).resolve()
    source_root = Path(args.source).resolve() if args.source else _default_source_root()

    ok, diagnostics = sync_standards(source_root, target_root, args.check)

    for line in diagnostics:
        print(line)

    if args.check:
        print("[PASS] standards mirrors are fresh" if ok else "[FAIL] standards mirrors are stale")
        return 0 if ok else 1

    print(f"[PASS] synced {len(diagnostics)} standard(s) from {source_root} to {target_root}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
