"""
Generate packages/bedrock-api/bedrock/schema/baseline.sql from MLBTracker.

The baseline is the platform's own tables — the ones bedrock's code queries
directly. It has to match what the code expects exactly, so it is derived
rather than hand-written.

    python tools/generate_baseline_sql.py --mlbtracker ../MLBTracker

Deriving it is less obvious than reading `schema_sqlite.sql`, because that file
does not describe the current schema. The auth tables are still there under
their pre-`auth_` names, and the diagnostics and audit tables were created by
migrations and renamed later. The only authoritative description of the current
platform schema is a database with the whole chain applied.

So that is what this does: bootstrap a throwaway SQLite database from
MLBTracker's schema, run its migrations, and dump the DDL SQLite itself
reports for the platform tables. Whatever the code runs against is what gets
written.

The table list is not hardcoded either — it comes from the package's own schema
catalog, which is what every bedrock query resolves names through. A catalog
table with no table in the built database fails the run rather than producing a
baseline that is quietly missing one.
"""
from __future__ import annotations

import argparse
import os
import pathlib
import sqlite3
import sys
import tempfile

HEADER = """\
-- bedrock platform baseline schema
--
-- Generated by tools/generate_baseline_sql.py; do not edit by hand. Dumped
-- from a database built by applying MLBTracker's full migration chain, which
-- is the only authoritative description of the current platform schema.
--
-- These are the tables bedrock's own code queries: app config, the grid config
-- store (global + per-user), auth, the log and audit stream, the import/export
-- run ledger, diagnostics, and migration bookkeeping.
--
-- An application applies this first, then layers its own migrations on top.
"""


def platform_tables(pkg_root: pathlib.Path) -> set[str]:
    """:returns: Every table name in the package's schema catalog."""
    sys.path.insert(0, str(pkg_root))
    from bedrock.core.schema_catalog import Tables  # noqa: PLC0415

    return {
        v for k, v in vars(Tables).items()
        if not k.startswith("_") and isinstance(v, str)
    }


def build_database(mlbtracker: pathlib.Path, db_path: str) -> None:
    """Bootstrap `db_path` from MLBTracker's schema and apply its migrations.

    The DatabaseManager singleton is repointed directly rather than through
    environment variables — the same thing MLBTracker's own conftest does,
    because the path is resolved at import time and an env var set afterwards
    is simply ignored.
    """
    sys.path.insert(0, str(mlbtracker))

    schema = (mlbtracker / "api" / "core" / "schema_sqlite.sql").read_text(
        encoding="utf-8")
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(schema)
        conn.commit()
    finally:
        conn.close()

    from api.core.database import db  # noqa: PLC0415
    from api.core import migrations  # noqa: PLC0415
    import api.domain.migration_content  # noqa: F401,PLC0415  (registers content)

    db.sqlite_path = db_path
    db.is_postgres = False
    db.db_url = None
    db.close_pool()

    migrations.apply_migrations()


def dump_ddl(db_path: str, wanted: set[str]) -> tuple[list[str], int]:
    """:returns: (DDL statements in dependency order, index count)."""
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT type, name, tbl_name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND type IN ('table', 'index') "
            "ORDER BY rootpage"
        ).fetchall()
    finally:
        conn.close()

    tables = {r[2]: r[3] for r in rows if r[0] == "table" and r[2] in wanted}
    missing = sorted(wanted - set(tables))
    if missing:
        print("FAIL: catalog tables absent from the built database:",
              file=sys.stderr)
        for t in missing:
            print("  " + t, file=sys.stderr)
        raise SystemExit(1)

    indexes: dict[str, list[str]] = {}
    n_idx = 0
    for kind, _name, tbl, sql in rows:
        if kind == "index" and tbl in wanted:
            indexes.setdefault(tbl, []).append(sql)
            n_idx += 1

    out: list[str] = []
    # rootpage order is creation order, which respects foreign keys.
    for _kind, _name, tbl, _sql in rows:
        if _kind != "table" or tbl not in tables or tbl in {o for o in out}:
            continue
        if any(s.startswith(f"CREATE TABLE {tbl}") or f" {tbl} (" in s
               for s in out):
            continue
        out.append(_normalise(tables.pop(tbl)))
        out.extend(_normalise(s) for s in indexes.get(tbl, []))
        out.append("")
    return out, n_idx


def _normalise(sql: str) -> str:
    """Add `IF NOT EXISTS` and a terminating semicolon.

    SQLite reports DDL as originally written, minus `IF NOT EXISTS`. An app
    applies the baseline before its own migrations, some of which may create
    the same table, so idempotence matters.
    """
    sql = sql.strip()
    for prefix in ("CREATE TABLE ", "CREATE UNIQUE INDEX ", "CREATE INDEX "):
        if sql.startswith(prefix) and "IF NOT EXISTS" not in sql:
            sql = prefix + "IF NOT EXISTS " + sql[len(prefix):]
            break
    return sql if sql.endswith(";") else sql + ";"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mlbtracker", required=True, type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path(__file__).resolve().parents[1]
                    / "packages" / "bedrock-api" / "bedrock" / "schema"
                    / "baseline.sql")
    args = ap.parse_args()

    wanted = platform_tables(args.out.parents[2])

    with tempfile.TemporaryDirectory() as tmp:
        db_path = os.path.join(tmp, "baseline.db")
        build_database(args.mlbtracker.resolve(), db_path)
        statements, n_idx = dump_ddl(db_path, wanted)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + "\n" + "\n".join(statements).rstrip() + "\n", encoding="utf-8")

    n_tables = sum(1 for s in statements if s.startswith("CREATE TABLE"))
    print(f"wrote {n_tables} tables + {n_idx} indexes to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
